/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: a                                                     *
* Dimensions:  86 * 26                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"
#include <stdint.h>
#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

#include "FocusFrame.h"
#define BITSPERPIXEL 8
#define FOCUS_WIDTH 3 //聚焦框的宽度
#define UPPER_WIDTH 5 //往上突出的长度



ForceDiretion_S  * currentForce = NULL;
ForceDiretion_S  button;
ForceDiretion_S  checkbox;
ForceDiretion_S  dropdown;
ForceDiretion_S  edit;
ForceDiretion_S  listbox;
ForceDiretion_S  listview;
ForceDiretion_S  radio;
ForceDiretion_S  scroll;
ForceDiretion_S  slider;
ForceDiretion_S  spinbox;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
//白和红调色板
static GUI_CONST_STORAGE GUI_COLOR _Colorsa[] = {
  0xFFFFFF, 0x241CED
};


static GUI_CONST_STORAGE GUI_LOGPALETTE _Pala = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsa[0]
};

//白和蓝调色板
static GUI_CONST_STORAGE GUI_COLOR _Colorsa2[] = {
  0xFFFFFF, 0xDB1809
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Pala2 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsa2[0]
};



 GUI_BITMAP Button_Focus;
 GUI_BITMAP ListBox_Focus;
 GUI_BITMAP ListView_Focus;
 GUI_BITMAP Radio_Focus;
 GUI_BITMAP Scroll_Focus;


//整个框
void focusWholeFrameInit( GUI_BITMAP * tBitMap, uint16_t tLength, uint16_t tWidth)
{

    unsigned char * tmp;
    uint32_t i = 0;
    uint32_t j = 0;
    tmp = (unsigned char *)malloc(tLength*tWidth);
    (*tBitMap).XSize = tLength;
    (*tBitMap).YSize = tWidth;
    (*tBitMap).BytesPerLine = tLength;
    (*tBitMap).BitsPerPixel = BITSPERPIXEL;
    (*tBitMap).pPal = &_Pala;

    for(j = 0; j < FOCUS_WIDTH; j++)
    {
      for(i = 0; i < tLength; i++)
      {
        tmp[i + j* tLength] = 0x01;
      }
    }
    
    for(j = FOCUS_WIDTH; j < tWidth -FOCUS_WIDTH; j++)
    {
      for(i = 0; i < tLength; i++)
      {
        if((i < FOCUS_WIDTH) ||(i >= tLength-FOCUS_WIDTH))
          tmp[i + j * tLength] = 0x01;
        else
          tmp[i + j * tLength] = 0x00;
      }
    }

    for(j = tWidth - FOCUS_WIDTH ; j < tWidth; j++)
    {
      for(i = 0; i < tLength; i++)
      {
        tmp[i + j * tLength] = 0x01;
      }
    }
    (*tBitMap).pData = tmp;


}

/**
 * 向上的小半个聚焦框
 * @param tBitMap 返回的聚焦框的bitmap
 * @param tLength 长度
 */
void focusUpFrameInit( GUI_BITMAP * tBitMap, uint16_t tLength)
{

    unsigned char * tmp;
    uint32_t i = 0;
    uint32_t j = 0;
    tmp = (unsigned char *)malloc(tLength*(UPPER_WIDTH + FOCUS_WIDTH));
    (*tBitMap).XSize = tLength;
    (*tBitMap).YSize = (UPPER_WIDTH + FOCUS_WIDTH);
    (*tBitMap).BytesPerLine = tLength;
    (*tBitMap).BitsPerPixel = BITSPERPIXEL;
    (*tBitMap).pPal = &_Pala;


    
    for(j = 0; j < UPPER_WIDTH; j++)
    {
      for(i = 0; i < tLength; i++)
      {
        if((i < FOCUS_WIDTH) ||(i >= tLength-FOCUS_WIDTH))
          tmp[i + j * tLength] = 0x01;
        else
          tmp[i + j * tLength] = 0x00;
      }
    }

    for(j = UPPER_WIDTH ; j < UPPER_WIDTH + FOCUS_WIDTH; j++)
    {
      for(i = 0; i < tLength; i++)
      {
        tmp[i + j * tLength] = 0x01;
      }
    }
    (*tBitMap).pData = tmp;


}

/**
 * 向下的小半个聚焦框
 * @param tBitMap 返回的聚焦框的bitmap
 * @param tXSize 控件的长度
 */
void focusDownFrameInit( GUI_BITMAP * tBitMap, uint16_t tXSize)
{

    unsigned char * tmp;
    uint32_t i = 0;
    uint32_t j = 0;
    tXSize = tXSize + 6;
    tmp = (unsigned char *)malloc(tXSize*(UPPER_WIDTH + FOCUS_WIDTH));
    (*tBitMap).XSize = tXSize;
    (*tBitMap).YSize = (UPPER_WIDTH + FOCUS_WIDTH);
    (*tBitMap).BytesPerLine = tXSize;
    (*tBitMap).BitsPerPixel = BITSPERPIXEL;
    (*tBitMap).pPal = &_Pala;


    for(j = 0 ; j <   FOCUS_WIDTH; j++)
    {
      for(i = 0; i < tXSize; i++)
      {
        tmp[i + j * tXSize] = 0x01;
      }
    }
    for(j = FOCUS_WIDTH; j < UPPER_WIDTH + FOCUS_WIDTH; j++)
    {
      for(i = 0; i < tXSize; i++)
      {
        if((i < FOCUS_WIDTH) ||(i >= tXSize-FOCUS_WIDTH))
          tmp[i + j * tXSize] = 0x01;
        else
          tmp[i + j * tXSize] = 0x00;
      }
    }
    (*tBitMap).pData = tmp;


}

/**
 * 改变聚焦框的颜色
 * @param tBitMap 需要改变的聚焦框的bitmap
 * @param tNum    颜色序号
 */
void focusChangeFrameColor(GUI_BITMAP * tBitMap, uint16_t tNum)
{
  if(tNum == 0)
    (*tBitMap).pPal =  &_Pala;
  else
    (*tBitMap).pPal =  &_Pala2;

}
/*************************** End of file ****************************/


/**
 * 初始化个元素的方向和值
 * @param tCreateInfo 设定的值
 * @param tDir        需要初始化的元素
 * @param tItem       元素在WM中的句柄
 * @param tUp         上方向的值
 * @param tDown       下方向的值
 * @param tLeft       左方向的值
 * @param tRight      右方向的值
 */
void focusDirectionInit(GUI_WIDGET_CREATE_INFO tCreateInfo, ForceDiretion_S * tDir,WM_HWIN tItem , ForceDiretion_S * tUp, ForceDiretion_S * tDown, ForceDiretion_S * tLeft, ForceDiretion_S * tRight)
{
  (*tDir).value = tItem;
    (*tDir).left = tLeft;
    (*tDir).right = tRight;
    (*tDir).up = tUp;
    (*tDir).down = tDown;
    (*tDir).x = tCreateInfo.x0 - FOCUS_WIDTH;
    (*tDir).y = tCreateInfo.y0 - FOCUS_WIDTH;//+ tCreateInfo.ySize 

}

/**
 * 失去焦点
 */
void focusDoLose(void)
{
    WM_SetFocus(WM_GetDesktopWindow());
}
