/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END 
#include "UKeyBoard.h"

#include "GTFont.h"
#include "FocusFrame.h"


#include "DIALOG.h"

extern GUI_BITMAP Button_Focus;
extern GUI_BITMAP ListBox_Focus;
extern GUI_BITMAP ListView_Focus;
extern GUI_BITMAP Radio_Focus;
extern GUI_BITMAP Scroll_Focus;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x02)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x03)
#define ID_EDIT_0 (GUI_ID_USER + 0x04)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x05)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x06)
#define ID_RADIO_0 (GUI_ID_USER + 0x07)
#define ID_SCROLLBAR_0 (GUI_ID_USER + 0x08)
#define ID_SLIDER_0 (GUI_ID_USER + 0x09)
#define ID_SPINBOX_0 (GUI_ID_USER + 0x0A)



  WM_HWIN win;
  
// USER START (Optionally insert additional defines)
// USER END


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 53, 40, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 158, 41, 80, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 276, 40, 80, 38, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 419, 42, 80, 20, 0, 0x64, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 572, 47, 133, 111, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 62, 143, 160, 79, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 317, 150, 80, 40, 0, 0x1402, 0 },
  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_0, 519, 174, 189, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 81, 304, 137, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 319, 308, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};




void directionInit(WM_MESSAGE * pMsg)
{
    WM_HWIN tItem;
    currentForce = &button;

   //(pMsg->hWin, ID_WINDOW_0);

    tItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    focusDirectionInit(_aDialogCreate[1], &button, tItem, NULL, &listview, NULL, &checkbox);

    tItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    focusDirectionInit(_aDialogCreate[2],&checkbox, tItem, NULL, &radio, &button, &dropdown);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    focusDirectionInit(_aDialogCreate[3],&dropdown, tItem, NULL, &radio, &checkbox, &edit);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    focusDirectionInit(_aDialogCreate[4],&edit, tItem, NULL, &scroll, &dropdown, &listbox);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    focusDirectionInit(_aDialogCreate[5],&listbox, tItem, NULL, &scroll, &edit, NULL);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    focusDirectionInit(_aDialogCreate[6],&listview, tItem, &button, &slider, NULL, &radio);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    focusDirectionInit(_aDialogCreate[7],&radio, tItem, &checkbox, &slider , &listview, &scroll);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_SCROLLBAR_0);
    focusDirectionInit(_aDialogCreate[8],&scroll, tItem, &listbox, &spinbox, &radio, NULL);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    focusDirectionInit(_aDialogCreate[9],&slider, tItem, &listview, NULL, NULL, &spinbox);
    
    tItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    focusDirectionInit(_aDialogCreate[10],&spinbox, tItem, &radio, NULL, &slider, NULL);

    focusDownFrameInit(&Button_Focus, _aDialogCreate[1].xSize );
    focusDownFrameInit(&ListBox_Focus, _aDialogCreate[5].xSize );
    focusDownFrameInit(&ListView_Focus, _aDialogCreate[6].xSize );
    focusDownFrameInit(&Radio_Focus, _aDialogCreate[7].xSize );
    focusDownFrameInit(&Scroll_Focus, _aDialogCreate[8].xSize );

    button.focusP = &Button_Focus;
    checkbox.focusP = &Button_Focus;
    dropdown.focusP = &Button_Focus;
    edit.focusP = &Button_Focus;
    listbox.focusP = &ListBox_Focus;
    listview.focusP = &ListView_Focus;
    radio.focusP = &Radio_Focus;
    scroll.focusP = &Scroll_Focus;
    slider.focusP = &Scroll_Focus;
    spinbox.focusP = &Button_Focus;
}

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
WM_MESSAGE * TEST;

// USER START (Optionally insert additional static code)
// USER END
extern GUI_FONT user_font;
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  TEST = pMsg;
    directionInit(pMsg);

    WINDOW_SetBkColor(pMsg->hWin, 0x00ED9A94);
    //
    // Initialization of 'Checkbox'
    //
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GTFont_15X16_8x16_HZ);
    BUTTON_SetText(hItem, "按钮");


    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetFont(hItem, &GTFont_15X16_8x16_HZ);
    CHECKBOX_SetTextColor(hItem, GUI_RED);
    CHECKBOX_SetText(hItem, "勾选框");
    
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem, &GUI_Font16_ASCII);
    DROPDOWN_AddString(hItem, "1");
    DROPDOWN_AddString(hItem, "2");
    DROPDOWN_AddString(hItem, "3");
    DROPDOWN_SetAutoScroll(hItem, 1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFont(hItem, &GUI_Font16_ASCII);
    // EDIT_SetTextColor(hItem,EDIT_CI_ENABLED, GUI_RED);
    EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_WHITE);
    EDIT_SetDecMode(hItem, 0, 0, 100000, 0,0);
    EDIT_SetValue(hItem, 123);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetFont(hItem, &GTFont_15X16_8x16_HZ);
    LISTBOX_AddString(hItem, "行1");
    LISTBOX_AddString(hItem, "行2");
    LISTBOX_AddString(hItem, "行3");
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 30, "行1", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 30, "Col 1", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 30, "Col 2", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetFont(hItem, &GTFont_15X16_8x16_HZ);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetFont(hItem, &GTFont_15X16_8x16_HZ);
    RADIO_SetText(hItem, "单选框", 0);
    RADIO_SetText(hItem, "2", 1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    // 
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);

    EDIT_SetValue(hItem, 8888);

        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

// void WMSETTEXT()
// {
//   WM_HWIN hItem;
//     hItem = WM_GetDialogItem(TEST->hWin, ID_EDIT_0);
//                       EDIT_SetValue(hItem,123);
//     //                   EDIT_SetText(hItem, "123");
//     //                       EDIT_SetFont(hItem, &GTFont_15X16_8x16_HZ);
//     // EDIT_SetTextColor(hItem,EDIT_CI_ENABLED, GUI_RED);
//     // EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_BLUE);

// }

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
extern void LcdDrawLine(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t tColor);

WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) 
	{
  WM_HWIN hWin;
  //CHECKBOX_SKINFLEX_PROPS tButtonProps ;
  CHECKBOX_SetDefaultSkin(CHECKBOX_SKIN_FLEX);    
  BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX); 
  DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX); 
  SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
  SCROLLBAR_SetDefaultSkin(SCROLLBAR_SKIN_FLEX);
  RADIO_SetDefaultSkin(RADIO_SKIN_FLEX);
  SPINBOX_SetDefaultSkin(SPINBOX_SKIN_FLEX);
  WIDGET_SetDefaultEffect(&WIDGET_Effect_3D);
// BUTTON_GetSkinFlexProps(&tButtonProps, BUTTON_SKINFLEX_PI_FOCUSSED);
// tButtonProps.aColorFrame[0] = GUI_RED;
// tButtonProps.aColorFrame[1] = GUI_LIGHTRED;
// BUTTON_SetSkinFlexProps(&tButtonProps, BUTTON_SKINFLEX_PI_FOCUSSED);

// BUTTON_GetSkinFlexProps(&tButtonProps, BUTTON_SKINFLEX_PI_PRESSED);
// tButtonProps.aColorFrame[0] = GUI_DARKRED;
// tButtonProps.aColorFrame[1] = GUI_LIGHTRED;
// tButtonProps.aColorFrame[2] = GUI_RED;
// tButtonProps.aColorLower[0] = GUI_RED;
// tButtonProps.aColorLower[1] = GUI_RED;
// tButtonProps.aColorUpper[0] = GUI_LIGHTRED;
// tButtonProps.aColorUpper[1] = GUI_LIGHTRED;

// BUTTON_SetSkinFlexProps(&tButtonProps, BUTTON_SKINFLEX_PI_FOCUSSED);

// CHECKBOX_SetDefaultFocusColor(GUI_RED);
// 
BUTTON_SetDefaultFocusColor(GUI_RED);
RADIO_SetDefaultFocusColor(GUI_RED);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/




